// public class Object {
//     public static void main(String[] args) {
//         Laptop o1 = new Laptop();
//         o1.model = "Lenovo";
//         o1.price = 1233;

//         Laptop o2 = new Laptop();
//         o2.model = "Lenovo";
//         o2.price = 1233;

//         // to generata hashcode of something.
//         System.out.println(o1.model.hashCode());

//         // equals - a method of object class.
//         boolean result = o1.equals(o2);
//         System.out.println(result);


//         // default it calls to string method
//         // toString() - it returns values can be checked by CTRL + LMB.
//         System.out.println(o1);
//         System.out.println(o1.toString());


//     }
// }


// class Laptop{
//     String model;
//     int price;

//     // overriding.
//     // public String toString(){
//     //     return "hey";
//     // }

//     // public boolean equals(Laptop that){
//     //     if(this.model.equals(that.model)&& this.price == that.price){
//     //         return true;
//     //     }
//     //     else{
//     //         return false;
//     //     }
//     // }


//     // generated by ide itself by source action on right click on mouse.
//     @Override
//     public int hashCode() {
//         final int prime = 31;
//         int result = 1;
//         result = prime * result + ((model == null) ? 0 : model.hashCode());
//         result = prime * result + price;
//         return result;
//     }

//     @Override
//     public boolean equals(java.lang.Object obj) {
//         if (this == obj)
//             return true;
//         if (obj == null)
//             return false;
//         if (getClass() != obj.getClass())
//             return false;
//         Laptop other = (Laptop) obj;
//         if (model == null) {
//             if (other.model != null)
//                 return false;
//         } else if (!model.equals(other.model))
//             return false;
//         if (price != other.price)
//             return false;
//         return true;
//     }

//     @Override
//     public String toString() {
//         return "Laptop [model=" + model + ", price=" + price + "]";
//     }


    
// }